### PR TITLE
"Fixed" :trollface: the inability to delete the first location by add…

### PR DESCRIPTION
**Pull request by rainrivas**
…ing a hacking solution -- i.e. added a unique locator to the first fav location we hardcoded in the html and bound an event to that delete icon.

Additionally moved the plus icon to the first label (also added to fav location) div and flushed it to the right to make it easier to add/delete things.

### CODE REVIEW

**Comment by rainrivas** [comment]
**KNOWN ISSUES** -- when there is only 1 favorite location, hitting enter will "submit" that one location and will clear the forms. This is because it's calling the submit CTA; however when we add subsequent fields, none of the fav locations will call submit CTA by pressing enter. We will need to fix up the form submissions in the future also probably get rid of YUI since its so old and dated

**Comment by jwu910** [comment]
Dude so everytime i pull a PR, it merges in to my stuff. Do i want that?

So long as I dont push it, it's not written to history and i can jsut reset and wipe changes right?

**Comment by rainrivas** [comment]
@jwu910 yeah you can just not push your changes.. but why are you pulling the PR? Are you pulling the pr into one of your custom local branches? or are you saying "when i checkout the branch the PR is on, i.e. delete-favInput, it pulls the 'pr changes' into my branch" 
cause if you saying the second one that's normal, that is just a git pull. The changes you pulled live on the repo for everyone to see

**Comment by jwu910** [comment]
Code looks good to me. 

Also realized that enter bug submitting the form happens onthe first fav location, but after you add more, i dont think it produces the same effect.

**Comment by rainrivas** [comment]
@jwu correct, i see the same

**Comment by rainrivas** [comment]
@jwu910 correct,  i see the same thing. Not too sure why that is the case. We are kind going blind here ao I'm thinking of taking a step back and building a prototype,  unless this is the prototype and we do it wth just min specs

**Comment by rainrivas** [comment]
@jwu910 @phuchle @psyduc @AlChiu can you guys give this a verdict (approval or needs changes)

**Comment by jwu910** [comment]
Code looks good. it works on my end (in terms of deleting the first fav location).

Need new branch to address the issue of preventDefault on the form fields. 

See discord for further discussion.

**Review by jwu910 — APPROVED** [review]
Still have console logs in. Also, are there more elegant ways to grab $(this).parent().parent()?

**Pull request merged**
