### PR TITLE
Adding helper texts to the form fields

### PR DESCRIPTION
**Pull request by rainrivas**
Added helper texts to form fields (place holders/titles) and removed the dangling </link> closure that was not needed.

### CODE REVIEW

**Review by jwu910 — COMMENTED** [review]
I was looking for zip code validator before. did not know you can just add a pattern regex inline. cool stuff

**Comment by rainrivas** [comment]
@jwu910 yeah you can, the only downside is that this would only support US Zip codes which are 5 numbers. Should be fine for our purposes, but if we ever support other countries we might have to increase the zipcodes we accept

**Comment by jwu910** [comment]
I think we can modify that with country preferences later. But currently staying in the scope of the US seems doable.

**Review by phuchle — APPROVED** [review]
Looks good to me.  We may want to use a 3rd party library for forms and such in the future but this works for now.

**Comment by rainrivas** [comment]
@phuchle good idea. We could let some 3rd party form validator handle it. Also you guys can merge this whenever you think it's ready. The person who opens the PR doesn't close the PR usually :+1:

**Pull request merged**
